# Generated by Django 3.2.6 on 2021-08-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product1',
            old_name='name',
            new_name='pname',
        ),
    ]
